results_path: /home/jovyan/nkiselev/studying/landscape-hessian/code/results/cifar10.json
plot_save_path: /home/jovyan/nkiselev/studying/landscape-hessian/code/figs_accuracy_vs_differences/cifar10.pdf
num_samples: 100