results_path: /Users/kisnikser/Documents/GitHub/landscape-hessian/code/results/mnist.json
plot_save_path: /Users/kisnikser/Documents/GitHub/landscape-hessian/code/figs_accuracy_vs_differences/mnist.pdf
num_samples: 100