dataset_name: 'MNIST'  # 'MNIST', 'FashionMNIST', 'CIFAR10', 'CIFAR100', 
train_size: 50000
val_size: 1000
train_batch_size: 64
val_batch_size: 64
learning_rate: 1.0e-3
num_samples: 10
num_epochs: 1
input_size: 784  # 'MNIST': 784, 'FashionMNIST': 784, 'CIFAR10': 3072, 'CIFAR100': 3072
hidden_size_list: [4, 8, 16, 32, 64]
output_size: 10
num_layers_list: [3]
save_path: '/home/jovyan/nkiselev/studying/landscape-hessian/code/results/mnist.json'