dataset_name: 'MNIST'  # 'MNIST', 'FashionMNIST', 'CIFAR10', 'CIFAR100', 
train_size: 10000
train_batch_size: 64
learning_rate: 1.0e-3
num_epochs: 10
input_size: 768
hidden_size_list: [4, 8, 16, 32, 64]
output_size: 10
num_layers_list: [1, 3, 5, 7, 10]
save_path: '/home/jovyan/nkiselev/ssd_dnn_paper/results_extraction/mnist.json'