dataset_name: 'CIFAR100'  # 'MNIST', 'FashionMNIST', 'CIFAR10', 'CIFAR100', 
train_size: 10000
val_size: 1000
train_batch_size: 64
val_batch_size: 64
learning_rate: 1.0e-3
num_samples: 10
num_epochs: 10
input_size: 3072  # 'MNIST': 784, 'FashionMNIST': 784, 'CIFAR10': 3072, 'CIFAR100': 3072
hidden_size_list: [4, 8, 16, 32, 64]
output_size: 100
num_layers_list: [1, 3, 5, 7, 10]
save_path: '/home/jovyan/nkiselev/studying/landscape-hessian/code/results/cifar100.json'